version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: wecolok.db
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: zYxvaMVbyxBaW@Hz10Nm
      POSTGRES_DB: wecolok
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    container_name: wecolok.web
    restart: always
    ports:
      - "80:80"
    depends_on:
      - postgres

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    container_name: wecolok.api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./apps/api/.env
    depends_on:
      - postgres

volumes:
  postgres_data:
