version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: colok-postgres-db
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: zYxvaMVbyxBaW@Hz10Nm
      POSTGRES_DB: colok
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./dockerfiles/web.Dockerfile
      dockerfile: ./dockerfiles/Dockerfile
    ports:
      - "8080:80"
#      todo
#    depends_on:
#      - backend

volumes:
  postgres_data:
