version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: colok-postgres-db
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: zYxvaMVbyxBaW@Hz10Nm
      POSTGRES_DB: colok
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    container_name: colok-web
    restart: always
    ports:
      - "80:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
